'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funzionalità di salvataggio automatico My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property comboitems() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("comboitems"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("comboitems") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property biositems() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("biositems"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("biositems") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property imagelink() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("imagelink"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("imagelink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property biosnames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("biosnames"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("biosnames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property buttonnames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("buttonnames"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("buttonnames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property bannerlink() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("bannerlink"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("bannerlink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ppcurrentlink() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ppcurrentlink"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ppcurrentlink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property profilehexcode() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("profilehexcode"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("profilehexcode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property bannerfanart() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("bannerfanart"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("bannerfanart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property imagefanart() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("imagefanart"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("imagefanart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property bannerartwork() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("bannerartwork"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("bannerartwork") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property imageartwork() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("imageartwork"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("imageartwork") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property bannerdaily() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("bannerdaily"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("bannerdaily") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property imagedaily() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("imagedaily"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("imagedaily") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property userlist() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("userlist"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("userlist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property oelname() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("oelname"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("oelname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property oelcover() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("oelcover"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("oelcover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property oelmarket() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("oelmarket"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("oelmarket") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property oelprice() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("oelprice"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("oelprice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property oelink() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("oelink"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("oelink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property cstlink() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("cstlink"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("cstlink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property cstname() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("cstname"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("cstname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage() As String
            Get
                Return CType(Me("BckgrnImage"),String)
            End Get
            Set
                Me("BckgrnImage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage2() As String
            Get
                Return CType(Me("BckgrnImage2"),String)
            End Get
            Set
                Me("BckgrnImage2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage3() As String
            Get
                Return CType(Me("BckgrnImage3"),String)
            End Get
            Set
                Me("BckgrnImage3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage4() As String
            Get
                Return CType(Me("BckgrnImage4"),String)
            End Get
            Set
                Me("BckgrnImage4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage5() As String
            Get
                Return CType(Me("BckgrnImage5"),String)
            End Get
            Set
                Me("BckgrnImage5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage6() As String
            Get
                Return CType(Me("BckgrnImage6"),String)
            End Get
            Set
                Me("BckgrnImage6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage7() As String
            Get
                Return CType(Me("BckgrnImage7"),String)
            End Get
            Set
                Me("BckgrnImage7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage8() As String
            Get
                Return CType(Me("BckgrnImage8"),String)
            End Get
            Set
                Me("BckgrnImage8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SPcover() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("SPcover"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("SPcover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SPlink() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("SPlink"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("SPlink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SPname() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("SPname"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("SPname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property postname() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("postname"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("postname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property postcode() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("postcode"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("postcode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property postdate() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("postdate"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("postdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property postday() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("postday"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("postday") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage9() As String
            Get
                Return CType(Me("BckgrnImage9"),String)
            End Get
            Set
                Me("BckgrnImage9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage10() As String
            Get
                Return CType(Me("BckgrnImage10"),String)
            End Get
            Set
                Me("BckgrnImage10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BckgrnImage11() As String
            Get
                Return CType(Me("BckgrnImage11"),String)
            End Get
            Set
                Me("BckgrnImage11") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.anilist_html_ultimate_creator_2.My.MySettings
            Get
                Return Global.anilist_html_ultimate_creator_2.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
